name: Evento1

on:
    issues:
    issue_comment:

jobs:
    inspect-event:
        runs-on: ubuntu-24.04
        permissions:
            issues: write

        steps:
            - name: Inspect event
              run: |
                  echo "Event: ${{ github.event_name }}"
                  echo "Issue: ${{ github.event.issue.number }}"
                  echo "Issue title: ${{ github.event.issue.title }}"
                  echo "Issue comment: ${{ github.event.comment.body }}"
